export const standingConstants = {
    GET_STANDING_REQUEST: 'GET_STANDING_REQUEST',
    GET_STANDING_SUCCESS: 'GET_STANDING_SUCCESS',
    GET_STANDING_FAILURE: 'GET_STANDING_FAILURE',

    GET_TEAMS_REQUEST: 'GET_TEAMS_REQUEST',
    GET_TEAMS_SUCCESS: 'GET_TEAMS_SUCCESS',
    GET_TEAMS_FAILURE: 'GET_TEAMS_FAILURE'
};